# Generated by Django 3.1.4 on 2020-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
