# Generated by Django 3.1.4 on 2020-12-11 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='categories_list',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='customer',
            field=models.OneToOneField(limit_choices_to={'is_merchant': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
