# Generated by Django 3.1.4 on 2020-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201211_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='merchant',
        ),
        migrations.AddField(
            model_name='merchant',
            name='categories_list',
            field=models.TextField(default=''),
        ),
    ]
