# Generated by Django 3.1.4 on 2020-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201211_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='business_owner_name',
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='categories_list',
            field=models.TextField(blank=True),
        ),
    ]
