# Generated by Django 3.1.4 on 2020-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201212_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='merchant signup'),
        ),
    ]
