# Generated by Django 3.1.4 on 2020-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201212_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
